### ISSUE TITLE
支援卡筛选结果未正确显示

### ISSUE THREAD

**Issue by warsier** [wrrwrr111/pretty-derby#103]
支援卡筛选时先选“类型”再选“育成效果”时得到的结果不正确。
例如：选择“智力”->“训练效果提升”之后得到的结果仍然包含其他类型的卡片（速度、力量卡等）；
但反过来选择“训练效果提升”->“智力”之后会得到正确结果。

**Comment by wrrwrr111** [comment]
已修复
