### ISSUE TITLE
金色技能背景

### ISSUE THREAD

**Issue by rongcuid** [wrrwrr111/pretty-derby#114]
当前的金技能背景有些难以看清，是否可以让整个框高亮（像以前版本那样）？

**Comment by rongcuid** [comment]
以下图为例，旧版本最右边的几个技能，文字背景为金色。现版本仅有图标为金色。

所有技能页面都发生了变化。不是最近的，应该至少一个月以上了。

![Screenshot from 2022-08-27 13-20-05](https://user-images.githubusercontent.com/1312525/187041075-e73595ae-77c0-4f4a-9993-d253fa83eb14.png)

**Comment by wrrwrr111** [comment]
应该是tailwind配置的问题 我研究解决一下

**Comment by wrrwrr111** [comment]
vercel 切换到了nextjs 还在看有没有什么别的问题,
之前tailwind引用的material-tailwind这个库 , 他最近大更新了版本整个放弃之前的内容,
目前先修复了技能显示颜色问题, 不过色号是比较难找回来了.
