### ISSUE TITLE
[缺失事件] 角色キングへイロー

### ISSUE THREAD

**Issue by library545** [wrrwrr111/pretty-derby#17]
缺少事件: 
`マナーくらい常識よ？`

选项:
1. さすがです、お嬢様
2. 本当に一流だったんだな

PS:
似乎是升到三星之后才出现的事件？在事件旁有决胜服的标志，或许其它角色也存在同样的问题
![image](https://user-images.githubusercontent.com/20147091/111890950-47555900-8a29-11eb-9019-945656d3e510.png)

**Comment by fireattack** [comment]
粗略抽查了下，大部分角色的育成event数据库里都有（不管是1星还是3星），这个不知道为啥漏掉了。而且是所有3个都漏掉：
![image](https://user-images.githubusercontent.com/4130991/112194739-30ed0000-8bd7-11eb-89a2-05f8f48309fc.png)

另外还发现数据库里有些微妙的错误，比如ウイニングチケット的育成事件应该是叫`全力テスト！`
![image](https://user-images.githubusercontent.com/4130991/112194877-5843cd00-8bd7-11eb-90b2-5913818c2524.png)

但是数据库上的漏了感叹号

![image](https://user-images.githubusercontent.com/4130991/112194957-68f44300-8bd7-11eb-8ba5-750331114485.png)

难道数据文本不是游戏里直接提取的？

顺便一提，名称是キングヘイロー 不是 キングハイロー

**Comment by wrrwrr111** [comment]
数据目前来源还是gamewith 直接提取还在做 目前应该能找到事件和选项 不过结果还是在服务器端

**Comment by library545** [comment]
> 难道数据文本不是游戏里直接提取的？
楼下作者说来源是gamewith，那可能还真是手打的(= =; )...

> 顺便一提，名称是キングヘイロー 不是 キングハイロー
sry, modified

**Comment by library545** [comment]
> 数据目前来源还是gamewith 直接提取还在做 目前应该能找到事件和选项 不过结果还是在服务器端

辛苦，看了下目前已经有这个事件，这个issue我就关掉了
