### ISSUE TITLE
背、追いかけて 事件实际为多选，网站上是单选

### ISSUE THREAD

**Issue by sumneko** [wrrwrr111/pretty-derby#34]
![赛马娘1](https://user-images.githubusercontent.com/5213431/113157872-d9e9c980-926d-11eb-957e-8591a381d847.png)
![赛马娘3](https://user-images.githubusercontent.com/5213431/113158078-0bfb2b80-926e-11eb-9eb5-cd0830918e7c.png)
![赛马娘2](https://user-images.githubusercontent.com/5213431/113158093-0ef61c00-926e-11eb-82ed-e96dfac2fee6.png)

但是第二个选项没有任何效果，不知道是不是BUG，总之引以为戒

**Comment by wrrwrr111** [comment]
嗯 新卡一开始数据都不会很全 慢慢完善

**Comment by sumneko** [comment]
可能是我用词不恰当，引以为戒指的是不要像我这样好奇选了第二个选项导致啥都没有
