### ISSUE TITLE
支援卡信息错误

### ISSUE THREAD

**Issue by x956606865** [wrrwrr111/pretty-derby#40]
不确定是游戏更新的原因还是信息录入时候的原因，现在比如目白麦昆、亚马逊之类的，在不同等级提供的属性加持数据和我实际打开app看到的数据都不太一样，我又去其他网站查了下，应该确实是录入数据不太对。其他的卡我还没看，不过感觉应该也有或多或少的问题。
话说，这个数据的话，要不要想办法怎么搞出来让大家一起来维护？毕竟如果一个人的话，录数据很容易出问题，有时候老数据修改了也没法有效及时更新

**Comment by wrrwrr111** [comment]
支援卡数据是我从数据库里解包拿到的 数值应该没问题 
如果有差错应该是计算的时候有问题 
字段时limit5-limit50 我目前理解就是limit50=40就说明50级的时候上限时40

**Comment by x956606865** [comment]
哦哦，可以解包，那数据维护就方便多了。我这边主要就是看麦昆的得意率加成的时候，目前网站是40级以前，都是35的加成，但实际上我35级的麦昆，加成就已经有40了，应该是计算时候有点区别

**Comment by wrrwrr111** [comment]
"limit_lv5": -1,
          "limit_lv10": 5,
          "limit_lv15": -1,
          "limit_lv20": -1,
          "limit_lv25": 35,
          "limit_lv30": 35,
          "limit_lv35": -1,
          "limit_lv40": -1,
          "limit_lv45": 50,
          "limit_lv50": -1
是这样的 应该是中间可能会有插值的算法

**Comment by fireattack** [comment]
中间是差值的无误，不过现在育成卡的数据缺失了固有技能加的部分。
我根据[网上找的资料](https://twitter.com/ikenaikoto/status/1377240593772994566) 把固有的效果parse了一下，目前来看所有SSR的固有的加成都是一样的（`None`表示目前没有卡有这个固有）：

```py
guyou_bonus = {
    "友情ボーナス": 10,
    "やる気効果アップ": 15,
    "スピードボーナス": 1,
    "スタミナボーナス": 1,
    "パワーボーナス": 1,
    "根性ボーナス": 1,
    "賢さボーナス": 1,
    "トレーニング効果アップ": 5,
    "初期スピードアップ": 20,
    "初期スタミナアップ": 20,
    "初期パワーアップ": 20,
    "初期根性アップ": 20,
    "初期賢さアップ": 20,
    "初期絆ゲージアップ": 15,
    "レースボーナス": 5,
    "ファン数ボーナス": None,
    "ヒントLvアップ": None,
    "ヒント発生率アップ": 20,
    "得意率アップ": 20,
    "スピード限界値アップ": None,
    "スタミナ限界値アップ": None,
    "パワー限界値アップ": None,
    "根性限界値アップ": None,
    "賢さ限界値アップ": None,
    "イベント回復量アップ": None,
    "イベント効果アップ": None,
    "失敗率ダウン": 10,
    "体力消費ダウン": 5,
    "ミニゲーム効果アップ": None,
    "スキルPtボーナス": 1,
    "賢さ友情回復量アップ": None,
}
```

但是不清楚SR的固有是否加成会更少一些。

这个数据解包里有吗？

**Comment by wrrwrr111** [comment]
找到了相关的数据 unique_effect , 我之后从数据库里解出来展示出来
