### ISSUE TITLE
建议：适配一下屏幕高度

### ISSUE THREAD

**Issue by fireattack** [wrrwrr111/pretty-derby#52]
![QQ图片20210410211849](https://user-images.githubusercontent.com/4130991/114290089-95ff7d00-9a42-11eb-8e09-da4ad75e81c6.png)
现在竖屏看是这样，感觉不是很舒服

**Comment by wrrwrr111** [comment]
没有复现，我这里竖屏是正常的

**Comment by fireattack** [comment]
哦，我是先在横屏打开，然后再移动到副屏（竖屏）全屏

**Comment by wrrwrr111** [comment]
嗯 目前就育成页面主要是响应式的
