### ISSUE TITLE
育成界面增加空白位置

### ISSUE THREAD

**Issue by lintmx** [wrrwrr111/pretty-derby#54]
希望育成界面增加一个空白位置，用于放置游戏窗口，这样可以防止游戏遮挡部分页面。

最好是一个可选可调整大小的空白

![无标题](https://user-images.githubusercontent.com/10807435/114311645-252f9200-9b22-11eb-846b-015c0e8562f5.png)

**Comment by wrrwrr111** [comment]
重新优化了一下布局
