### ISSUE TITLE
馬娘事件缺漏

### ISSUE THREAD

**Issue by dwu1996** [wrrwrr111/pretty-derby#56]
似乎沒有「愉快ッ！密着取材！」這個事件。

**Comment by wrrwrr111** [comment]
事件来自gamewith 不知道为什么一直也没有这个事件

**Comment by dwu1996** [comment]
看看要不要手動加上吧......

愉快ッ！密着取材！
--
尊敬すべき理事長です：スタミナ+10/絆+5
暴走することが多いような：根性+10/絆+5

**Comment by wrrwrr111** [comment]
先手动添加了
