### ISSUE TITLE
技能-支援卡列表有时候卡面变得很小

### ISSUE THREAD

**Issue by fireattack** [wrrwrr111/pretty-derby#63]
Bad:
![image](https://user-images.githubusercontent.com/4130991/115348655-81289500-a178-11eb-875a-8b846ee95e75.png)
Good:
![image](https://user-images.githubusercontent.com/4130991/115348662-8554b280-a178-11eb-9095-0dcee67f0643.png)

**Comment by wrrwrr111** [comment]
在支援卡每种最多只有一个的时候 不明原因宽度计算有问题， 先修改了一下实现方式
