### ISSUE TITLE
時程規劃功能

### ISSUE THREAD

**Issue by helomair** [wrrwrr111/pretty-derby#74]
最近才想到的，但不確定能否實作
一個完整三年的表格，選好馬娘後會先把目標比賽給放上去，並且情人節或是合宿等特殊活動會有標示。
使用者可以根據自己的需求在表格中新增當日要做甚麼事，新增一個比賽進去之類的，沒有新增的日子就空著

**Comment by wrrwrr111** [comment]
有考虑在育成阶段得时间轴上显示ura剧情相关得内容
