### ISSUE TITLE
请问能否再改善下二级弹出界面？

### ISSUE THREAD

**Issue by Nankyoku-D** [wrrwrr111/pretty-derby#77]
开发者你好，

我在使用的过程中，会经常遇到弹出界面无法全部显示的情况，（使用的是13寸的笔记本）。
比如点击「角色」界面的「目白赖恩」，然后再将鼠标移到她的固有技能上，只能看到「触发条件」以下的部分，这之上的部分怎么都看不到。
在「支援卡」页面，点开卡面之后再去看技能也会遇到这种情况。
而不管是「角色」还是「支援卡」或者「技能」的一级弹出页面都是可以上下拖动的，希望可以改善成那样的情况。

**Comment by wrrwrr111** [comment]
技能加了最大的高度和滚动条
