### ISSUE TITLE
SR卡 スイープトウショウ 育成事件数据缺失

### ISSUE THREAD

**Issue by fireattack** [wrrwrr111/pretty-derby#8]
这卡有俩育成事件，网站上只有第一个事件获得的技能，没有第二个事件获得的技能。

暂时没有检查是否有其他错误

![image](https://user-images.githubusercontent.com/4130991/111479152-b61b7500-86fe-11eb-88a3-bd86113d03d4.png)
![image](https://user-images.githubusercontent.com/4130991/111479184-bd428300-86fe-11eb-9f29-90775d56ce0f.png)

![image](https://user-images.githubusercontent.com/4130991/111479201-c0d60a00-86fe-11eb-93e1-4abfbef9439c.png)

**Comment by wrrwrr111** [comment]
fixed
